### ISSUE TITLE
Has this Issue Been Resolved?

### ISSUE THREAD

**Issue by MakerDZ** [dugan-dev/safe-action-issue-reproduction#1]
I am trying to use this package. I am also using TurboRepo, which is why I am a bit concerned about still encountering the same error. If you have previously faced and resolved a similar error, could you please share how you solved it?

**Comment by CodeChooch4** [comment]
@MakerDZ It has not be resolved in a non-hacky way. My hacky work around is to type the return of each action I make as well as the safe action:

`export const action: ReturnType<typeof createSafeActionClient> =
  createSafeActionClient({
    handleReturnedServerError,
    async middleware() {
      const { userId } = auth();
      if (userId === null) {
        throw new Error("User not authenticated. Please log in and try again.");
      }
    },
  });
`
`export const createIfPossibleAction: ReturnType<typeof action> =
  action(schema, async ({ newFormData, revalidationPath }) => {
    const { userId } = auth();

    // Create new and return the public ID
    const new = await createIfPossible({
      newFormData,
      userId: userId ?? "",
    });

    if (revalidationPath) {
      revalidatePath(revalidationPath);
    }
    // Return the new Physician public ID
    return { newPubId: new.newPubId };
  });`

Not a great work around as then the types for the returns don't work properly so you end up have to `as` everything to make it work which kind of defeats the purpose. I'm just going with it for now in hopes of getting an answer from the author soon, if not I may just roll my own.

**Comment by CodeChooch4** [comment]
@MakerDZ The response to my issue did solve my problem. I recommend reviewing the response and seeing if it solves you issues as well.
